### ISSUE TITLE
Broken SDK produced when cloning

### ISSUE THREAD

**Issue by DiegoBM** [armory3d/armsdk#1]
OS: Windows 10
Blender: 2.79b

Following the instructions of the README.md and/or the official manual (https://armory3d.org/manual/#/dev/gitversion?id=manual-clone) will produce a broken SDK.
If you switch in blender the armory addon to use it, it will fail even for the basic example (new file -> save -> select cycles -> Click "Play" button).

The console output:

...
Compiling shader 7 of 8 (painter-video.frag.glsl).
Compiling shader 8 of 8 (painter-video.vert.glsl).
C:\\...\Armory\sdkmaster\armory\Sources/armory/system/Starter.hx:40: characters 46-76 : Class<kha.WindowOptions> has no field FeatureResizable
C:\\...\Armory\sdkmaster\armory\Sources/armory/system/Starter.hx:41: characters 48-80 : Class<kha.WindowOptions> has no field FeatureMaximizable
C:\\...\Armory\sdkmaster\armory\Sources/armory/system/Starter.hx:42: characters 48-80 : Class<kha.WindowOptions> has no field FeatureMinimizable
C:\\...\Armory\sdkmaster\armory\Sources/armory/system/Starter.hx:45: characters 129-143 : Int should be Null<kha.WindowFeatures>
C:\\...\Armory\sdkmaster\armory\Sources/armory/system/Starter.hx:45: characters 129-143 : Int should be kha.WindowFeatures
C:\\...\Armory\sdkmaster\armory\Sources/armory/system/Starter.hx:45: characters 129-143 : For function argument 'options'

Haxe compiler error.
Finished in 6.986127138137817
Build failed, check console

**Comment by luboslenco** [comment]
Fixed in 0.6!
