### ISSUE TITLE
[Suggestion] Tags For Armory Releases

### ISSUE THREAD

**Issue by zicklag** [armory3d/armsdk#2]
It would be good if for every armory release we updated this repo and tagged it with the release number ( i.e. 0.6-alpha0 ). That way it would be easy to go back to a release for testing. For example, once I wanted to checkout Armory 0.5 because somebody on the forums said that that was the version they had, and I didn't want to download a new build of Armory when I already have git and the plugin setup.

The binary repos like Krom would end up going out of date if we reset the Krom_bin git repo because of the size, but we could at least keep the last release or two.

**Comment by luboslenco** [comment]
Fixed now https://github.com/armory3d/armsdk/releases.
