### ISSUE TITLE
Auto-deploy API docs to armory3d.org/api

### ISSUE THREAD

**Issue by MoritzBrueckner** [armory3d/armsdk#28]
Thanks to https://github.com/armory3d/armsdk/pull/24 we now have a Github action that builds the latest API documentation on each release, however it's currently not deployed to armory3d.org/api ([source repo](https://github.com/armory3d/armory_api/tree/b1eb3ae96257fd2e61dbe69a5b757dfebdc45dc4)). Instead it's deployed to [armsdk/gh-pages](https://github.com/armory3d/armsdk/tree/gh-pages) which is not "connected" to the website. Is it possible to deploy to the actual API repo instead, then update the submodule [here](https://github.com/armory3d/armory_web/tree/gh-pages) and trigger a rebuild of the website?

**Comment by tong** [comment]
Another option could be to create a subdomain (like api.armory.org) and change the dns settings to point to the gh-pages of this repo (https://armory3d.github.io/armsdk).

See: https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-a-subdomain

**Comment by luboslenco** [comment]
https://api.armory3d.org/ is alive!

**Comment by MoritzBrueckner** [comment]
Thanks a lot! I think we should remove the old API docs then and redirect to the new URL, if that is possible with GitHub pages.
