### ISSUE TITLE
Installation doesn't work

### ISSUE THREAD

**Issue by anonimo82** [armory3d/armsdk#43]
Hello everyone.
I downloaded Armory from itch, but if I try to install the zip file, nothing happens, neither an error, nor the ability to enable it.

Please, can someone help?

Thanks

**Comment by MoritzBrueckner** [comment]
Hi and welcome,

please don't install the .zip file as such, you need to extract it first and then install the included armory.py. It's explained in more detail in the wiki: https://github.com/armory3d/armory/wiki/setup#installation.

**Comment by anonimo82** [comment]
Oh, thanks.
I was used to git clone this repo, but I had problems and guessed things were different.
Well then, cheers =)

**Comment by MoritzBrueckner** [comment]
> I was used to git clone this repo, but I had problems

When cloning this repo, don't forget the `--recursive` flag for the git clone command so that all submodules are also cloned.

**Comment by anonimo82** [comment]
Yes, I know, but I ran
`git submodule update`
or something similar, then I had the error

**Comment by anonimo82** [comment]
Yes, I know, but I ran
`git submodule update`
or something similar, then I had the error
