### ISSUE TITLE
Is the flash past due to a memory graphics card?

### ISSUE THREAD

**Issue by chuiliuyiyi** [armory3d/armsdk#63]
window10
blender3.3.0
armory2303
No graphics card
armory player  flash across，Is this the reason for not having a graphics card？

**Comment by rpaladin** [comment]
Hi. Please do not cross-post. Posting only in https://github.com/armory3d/armory is sufficiently enough :-)

**Comment by luboslenco** [comment]
Link to https://github.com/armory3d/armory/issues/2832.
