### ISSUE TITLE
Shipping a Krom build with fix for https://github.com/armory3d/armorcore/issues/52

### ISSUE THREAD

**Issue by e2002e** [armory3d/armsdk#68]
Is it possible for someone to compile Krom with the fixes mentionned in the title for Linux ?
You guys spotted the error and know how to fix it. I don't think there is anything else to do than that regarding this issue.

**Comment by luboslenco** [comment]
It should be fixed in the latest linux binary at https://github.com/armory3d/armorcore_bin.
